"""Entity users: add column code debd collector

Revision ID: 13f417cb23ad
Revises: 40557173f455
Create Date: 2022-10-24 23:14:54.142263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f417cb23ad'
down_revision = '40557173f455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code_debd_collector', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'code_debd_collector')
    # ### end Alembic commands ###
