"""add column status to model roles add default True

Revision ID: 40557173f455
Revises: 6b890b68717c
Create Date: 2022-10-23 13:27:53.223127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40557173f455'
down_revision = '6b890b68717c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'status')
    # ### end Alembic commands ###
