"""Add model documents

Revision ID: ab3de1136cc3
Revises: 13f417cb23ad
Create Date: 2022-10-28 17:16:24.574133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3de1136cc3'
down_revision = '13f417cb23ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_doc', sa.String(length=2), nullable=True),
    sa.Column('series', sa.String(length=4), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=True),
    sa.Column('process_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
