"""Create model User

Revision ID: cde448fbd8cf
Revises: 8005b40cdabd
Create Date: 2022-10-23 11:26:49.606597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde448fbd8cf'
down_revision = '8005b40cdabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=160), nullable=True),
    sa.Column('user_name', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
