"""add model document

Revision ID: d0b82554e00b
Revises: 13f417cb23ad
Create Date: 2022-10-29 09:07:51.014032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b82554e00b'
down_revision = '13f417cb23ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_doc', sa.String(length=2), nullable=True),
    sa.Column('series', sa.String(length=4), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('issue_date', sa.String(length=10), nullable=False),
    sa.Column('collect_date', sa.String(length=10), nullable=True),
    sa.Column('process_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
